name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Kontrolli rakenduse käivitumist
    runs-on: ubuntu-latest
    steps:
      - name: Lae kood alla
        uses: actions/checkout@v4

      - name: Käivita teenused Dockeriga
        run: docker-compose up -d

      - name: Oota teenuste käivitumist
        run: sleep 10

      - name: Kontrolli API Gateway staatust (Health check)
        run: |
          # Проверяем, отвечает ли API Gateway (порт 3000)
          curl -f http://localhost:3000/health || exit 1

      - name: Peata teenused
        run: docker-compose down